FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 python3-pip

RUN pip3 install flask flask-cors --break-system-packages

WORKDIR /app
COPY ./api.py /app/api.py

CMD ["python3", "/app/api.py"]